//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using System.Data;
    

    public partial class Contatti
    {
        [Key, ForeignKey("Contact")]
        public int ContattoID { get; set; }
        public string Nome { get; set; }
        public string Via { get; set; }
        public string Citta { get; set; }
        public string Stato { get; set; }
        public string CodicePostale { get; set; }
        public string Email { get; set; }
        [Required]
        public virtual ICollection<Contact> Contact { get; set; }
    }
}
