//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contatti
    {
        public int ContattoID { get; set; }
        public string Nome { get; set; }
        public string Via { get; set; }
        public string Citta { get; set; }
        public string Stato { get; set; }
        public string CodicePostale { get; set; }
        public string Email { get; set; }
    }
}
